#pragma once
const char LAMP_PAGE[] PROGMEM = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cool Lamp</title>
<style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#10151d;color:#e9eff6}*{box-sizing:border-box}body{max-width:760px;margin:auto;padding:28px 18px 60px}h1{font-size:36px;margin:0}h2{font-size:20px;margin:0 0 18px}.sub{color:#9eb0c4;line-height:1.5}section{background:#1a2431;border:1px solid #314154;border-radius:18px;padding:22px;margin:22px 0}label{display:block;margin:18px 0 7px;font-weight:600}input,select,button{font:inherit;padding:12px;border-radius:9px;border:1px solid #4c627c;width:100%;background:#101b29;color:#fff}button{background:#59dbc4;color:#062a26;border:0;font-weight:700;cursor:pointer;margin-top:18px}button.secondary{background:#304459;color:#eef4fa}button:disabled{opacity:.5;cursor:wait}input[type=checkbox]{width:auto;margin-right:10px}input[type=color]{height:56px;padding:4px}input[type=range]{padding:0;accent-color:#59dbc4}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.buttons{display:flex;gap:14px}.hint{font-size:13px;color:#a9bacb;line-height:1.5}#status{position:sticky;top:8px;padding:12px 16px;background:#253c47;border-radius:10px;z-index:2;min-height:44px}progress{width:100%;margin-top:14px;accent-color:#59dbc4}a{color:#7ce3d3}small{font-weight:normal;color:#a9bacb}@media(max-width:520px){.grid{grid-template-columns:1fr;gap:0}.buttons{display:block}section{padding:18px}}
</style></head><body><h1>Cool Lamp</h1><p class="sub">Make the light your own.</p><div id="status" role="status" aria-live="polite">Connecting to your lamp…</div>
<form id="settings"><section><h2>Light & effects</h2><label for="mode">Effect <small>also saved as the startup effect</small></label><select id="mode" name="mode" required></select><label for="color">Color for this effect</label><input id="color" type="color" value="#ff3c6e"><p id="colorHint" class="hint"></p><button id="applyColor" type="button">Apply color</button><button id="resetColor" type="button" class="secondary">Restore effect defaults</button>
<label for="speed">Speed <output id="speedValue"></output></label><input id="speed" type="range" min="1" max="100" value="50">
<label for="intensity">Intensity <output id="intensityValue"></output></label><input id="intensity" type="range" min="0" max="100" value="100">
<label><input id="dual" type="checkbox">Use two colors</label><label for="secondaryColor">Second color</label><input id="secondaryColor" type="color" value="#23a0ff">
<p class="hint">For original effects, apply a custom primary color to enable two colors. Speed applies to animated effects.</p>
<button id="applyOptions" type="button">Apply effect settings</button><label for="brightness">Brightness <output id="brightnessValue"></output></label><input id="brightness" name="brightness" type="range" min="1" max="255" value="100"><div class="buttons"><button id="preview" type="button">Preview light</button><button id="power" class="secondary" type="button">Toggle power</button></div><p class="hint">Preview changes are temporary. Save below to keep them after a restart.</p></section>
<section><h2>Strip configuration</h2><div class="grid"><div><label for="leds">Number of LEDs</label><input id="leds" name="leds" type="number" min="1" max="1024" required></div><div><label for="milliamps">LED power limit (mA at 5 V)</label><input id="milliamps" name="milliamps" type="number" min="100" max="20000" required></div></div><p class="hint">Set the LED count to the physical strip length. Keep the power limit within the supply and wiring capacity. The limit is an estimate for the LEDs; the controller also uses power.</p></section>
<section><h2>Home Wi-Fi</h2><p id="network" class="sub"></p><button id="scan" class="secondary" type="button">Find nearby networks</button><p id="scanStatus" class="hint" role="status"></p><label for="networks">Available networks</label><select id="networks"><option value="">Scan to find networks</option></select><label for="ssid">Network name (2.4 GHz)</label><input id="ssid" name="ssid" maxlength="32" autocomplete="off"><label for="wifiPassword">Network password</label><input id="wifiPassword" name="wifiPassword" type="password" maxlength="63" autocomplete="new-password" placeholder="Leave blank to keep the saved password"><label><input id="openNetwork" name="openNetwork" type="checkbox" value="1">This network has no password</label><label><input id="forgetWifi" name="forgetWifi" type="checkbox" value="1">Forget the saved Wi-Fi network</label><p class="hint">No home Wi-Fi is required for hotspot setup. Hold the knob for three seconds to open or close the hotspot. It closes after ten idle minutes.</p></section>
<section><h2>Access password</h2><label for="adminPassword">New hotspot & web password</label><input id="adminPassword" name="adminPassword" type="password" minlength="8" maxlength="63" autocomplete="new-password" placeholder="Leave blank to keep the current password"><p class="hint">Use 8–63 characters. The web username is <strong>lamp</strong>. A changed password applies after restart, including to the hotspot.</p><button id="save" type="submit">Save settings & restart</button><p class="hint">The light and web connection pause during restart. If you change the network or password, reconnect using the new details.</p></section></form>
<section><h2>Effect center</h2><form id="geometryForm"><label for="midpoint">Center after LED (0 = automatic)</label><input id="midpoint" type="number" min="0" max="1023" value="0" required><p class="hint">Count from the data-input end. The center lies between this LED and the next. Each side scales independently. Save LED-count changes first. If the strip gets shorter, the center is limited to its last boundary.</p><button id="saveGeometry">Save center point</button><p id="geometryStatus" role="status"></p></form></section><section><h2>Microphone</h2><label><input id="microphoneInstalled" type="checkbox">INMP441 microphone installed</label><p class="hint">Enable only on lamps fitted with a microphone. This controls which effects are available; silence does not mean the microphone is missing.</p><div class="grid"><div><label for="audioGain">Sensitivity <output id="audioGainValue">8</output></label><input id="audioGain" type="range" min="1" max="64" value="8"></div><div><label for="audioScale">Scale factor <output id="audioScaleValue">1.00×</output></label><input id="audioScale" type="range" min="100" max="400" step="5" value="100"><p class="hint">Higher scale makes quieter sounds dark while loud sounds still reach full brightness. Start at 2×. Sensitivity controls amplification.</p><label for="audioGate">Noise gate (0–1024)</label><input id="audioGate" type="number" min="0" max="1024" value="8"></div></div><button id="saveAudio" type="button">Save microphone settings & restart</button><button id="testAudio" class="secondary" type="button">Test microphone for 10 seconds</button><p id="audioStatus" class="hint" role="status"></p></section>
<section><h2>Firmware update</h2><p class="sub">Install a new Cool Lamp firmware file over Wi-Fi.</p><form id="firmware"><label for="image">ESP32-C3 application file (.ino.bin)</label><input id="image" type="file" accept=".bin" required><p class="hint">Choose the application file, not a bootloader, partitions, or merged image. Keep the lamp powered until the update finishes.</p><button id="upload" type="submit">Upload firmware & restart</button><progress id="progress" max="100" value="0" hidden></progress></form></section>
<section><h2>Phone app pairing</h2><p class="hint">Hold the knob for six seconds until the lamp flashes blue, then find the lamp in the app. No code is needed. Pairing closes after a phone pairs or after two minutes. Saved phones reconnect without setup.</p><button id="pairing" type="button">Check pairing status</button><p id="pairingStatus" role="status"></p><button id="forgetPhones" type="button" class="secondary">Forget all paired phones</button></section>
<section><h2>Online firmware updates</h2><p>Installed: <strong id="firmwareVersion">Loading…</strong></p><p id="firmwareStatus" role="status"></p><label><input id="autoUpdate" type="checkbox" disabled>Install updates automatically</label><p class="hint">Requires home Wi-Fi with internet access. Updates briefly pause the light and restart the lamp.</p><button id="checkFirmware" disabled>Check for updates</button><button id="installFirmware" disabled>Update now</button></section>
<script>
'use strict';
let token='',powerOn=true,colors=[],effectOptions=[],bannerOwner='general';const $=id=>document.getElementById(id);const status=(message,owner='general')=>{bannerOwner=owner;$('status').textContent=message};
async function request(path,data){const response=await fetch(path,{method:'POST',headers:{'X-Lamp-Token':token},body:new URLSearchParams(data)});const message=await response.text();if(!response.ok)throw new Error(message);return message}
function brightnessText(){$('brightnessValue').value=Math.round(Number($('brightness').value)*100/255)+'%'}
$('brightness').addEventListener('input',brightnessText);
async function load(){try{const r=await fetch('/api/state');if(!r.ok)throw new Error('Sign in using the lamp username and password, then refresh.');const s=await r.json();token=s.token;powerOn=s.power;$('midpoint').max=Math.max(0,s.leds-1);$('midpoint').value=s.midpoint?Math.min(s.midpoint,s.leds-1):0;if(s.audio){$('microphoneInstalled').checked=s.audio.installed;$('audioGain').value=s.audio.gain;$('audioGate').value=s.audio.gate;$('audioScale').value=s.audio.scale??100;audioLabels();}colors=s.colors||[];effectOptions=s.effectOptions||[];s.effects.forEach((name,i)=>{const option=new Option(name,i+1);$('mode').add(option)});$('mode').value=s.mode;colorText();$('brightness').value=s.brightness;$('leds').value=s.leds;$('milliamps').value=s.milliamps;$('ssid').value=s.ssid;brightnessText();$('network').textContent=s.connected?'Connected. Address: '+s.address+' • '+s.hostname:'Not connected to home Wi-Fi. You can still configure the lamp here.';status('Ready • '+s.effects.length+' effects')}catch(e){status(e.message)}}
function colorText(){const c=colors[Number($('mode').value)-1]||[0,255,60,110];$('color').value='#'+c.slice(1).map(v=>v.toString(16).padStart(2,'0')).join('');$('colorHint').textContent=c[0]?'Your color is active. Save settings to remember it.':'Original colors are active. Choose a color to customize this effect.';}
const originalColorText=colorText;
colorText=()=>{originalColorText();const mode=Number($('mode').value),o=effectOptions[mode-1]||[50,mode===31?35:100,mode>=30?1:0,35,160,255];
 $('speed').value=o[0];$('intensity').value=o[1];optionLabels();$('speed').disabled=mode>=21&&mode<=29;
 $('dual').checked=Boolean(o[2]);$('secondaryColor').disabled=!o[2];$('secondaryColor').value='#'+o.slice(3).map(v=>v.toString(16).padStart(2,'0')).join('');};
function optionLabels(){$('speedValue').value=$('speed').value+'%';$('intensityValue').value=$('intensity').value+'%'}
$('speed').oninput=optionLabels;$('intensity').oninput=optionLabels;
$('dual').onchange=()=>{$('secondaryColor').disabled=!$('dual').checked};
$('applyOptions').onclick=async()=>{const mode=Number($('mode').value),h=$('secondaryColor').value.slice(1),rgb=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)),o=[Number($('speed').value),Number($('intensity').value),Number($('dual').checked),...rgb];
 $('applyOptions').disabled=true;try{status(await request('/api/effect-options',{mode,speed:o[0],intensity:o[1],dual:o[2],r:o[3],g:o[4],b:o[5]}));effectOptions[mode-1]=o;if(Number($('mode').value)===mode)colorText()}catch(e){status(e.message)}finally{$('applyOptions').disabled=false}};
$('mode').onchange=colorText;
$('applyColor').onclick=async()=>{const mode=Number($('mode').value),h=$('color').value.slice(1),rgb=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16));try{status(await request('/api/color',{mode,r:rgb[0],g:rgb[1],b:rgb[2]}));colors[mode-1]=[1,...rgb];colorText()}catch(e){status(e.message)}};
$('resetColor').onclick=async()=>{const mode=Number($('mode').value);try{status(await request('/api/color',{mode,reset:1}));colors[mode-1]=mode===3?[0,128,160,255]:mode===31?[1,190,215,255]:mode===33?[1,255,200,60]:[mode>=29?1:0,255,60,110];effectOptions[mode-1]=[50,mode===31?35:100,mode>=30?1:0,35,160,255];colorText()}catch(e){status(e.message)}};
$('preview').onclick=async()=>{try{status(await request('/api/preview',{mode:$('mode').value,brightness:$('brightness').value}));powerOn=true}catch(e){status(e.message)}};
$('power').onclick=async()=>{try{status(await request('/api/power',{on:powerOn?'0':'1'}));powerOn=!powerOn}catch(e){status(e.message)}};
$('settings').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{status(await request('/api/config',new FormData(e.target)));$('wifiPassword').value='';$('adminPassword').value=''}catch(error){status(error.message);$('save').disabled=false}};
$('firmware').onsubmit=e=>{e.preventDefault();const file=$('image').files[0];if(!file)return;const data=new FormData();data.append('firmware',file);const xhr=new XMLHttpRequest();xhr.open('POST','/update');xhr.setRequestHeader('X-Lamp-Token',token);$('upload').disabled=true;$('progress').hidden=false;xhr.upload.onprogress=e=>{if(e.lengthComputable){$('progress').value=e.loaded*100/e.total;status('Uploading firmware… '+Math.round($('progress').value)+'%')}};xhr.onload=()=>{status(xhr.responseText||'No response from lamp.');if(xhr.status!==200)$('upload').disabled=false};xhr.onerror=()=>{status('Connection interrupted. Reconnect to the lamp and check its status before retrying.');$('upload').disabled=false};status('Starting firmware upload…');xhr.send(data)};
$('scan').onclick=async()=>{
  $('scan').disabled=true;$('scanStatus').textContent='Looking for nearby 2.4 GHz networks…';
  try{
    await request('/api/scan',{});
    const deadline=Date.now()+30000;
    while(Date.now()<deadline){
      await new Promise(resolve=>setTimeout(resolve,750));
      const r=await fetch('/api/scan',{signal:AbortSignal.timeout(5000)});
      if(!r.ok)throw new Error('Could not read networks. Refresh the page and try again.');
      const result=await r.json();
      if(result.status==='scanning')continue;
      if(result.status!=='complete')throw new Error('Scan could not finish. Try again in a few seconds, or enter the network name below.');
      $('networks').replaceChildren(new Option('Choose a network…',''));
      result.networks.forEach(n=>{const option=new Option(n.ssid+' • '+(n.rssi>=-60?'Strong':n.rssi>=-75?'Good':'Weak')+' • '+(n.open?'Open':'Password required'),n.ssid);option.dataset.open=String(n.open);$('networks').add(option)});
      $('scanStatus').textContent=result.networks.length+' networks found. Hidden networks can be entered below.';
      return;
    }
    throw new Error('Scan timed out. Try again.');
  }catch(e){$('scanStatus').textContent=e.message}finally{$('scan').disabled=false}
};
$('networks').onchange=()=>{const option=$('networks').selectedOptions[0];if(!option.value)return;$('ssid').value=option.value;$('openNetwork').checked=option.dataset.open==='true';$('forgetWifi').checked=false;$('wifiPassword').value=''};
$('pairing').onclick=async()=>{try{const r=await fetch('/api/bluetooth',{cache:'no-store'});if(!r.ok)throw new Error('Sign in again to read pairing status.');const s=await r.json();$('pairingStatus').textContent=!s.enabled?'Bluetooth is disabled in this firmware.':s.pairing?'Ready to pair. Find CoolLamp in the app.':'Pairing is closed. Hold the knob for six seconds until the lamp flashes blue.'}catch(e){$('pairingStatus').textContent=e.message}};
$('forgetPhones').onclick=async()=>{if(!confirm('Remove Bluetooth access for every saved phone?'))return;try{$('pairingStatus').textContent=await request('/api/bluetooth/forget',{})}catch(e){$('pairingStatus').textContent=e.message}};
let firmwareStatus=null,firmwareBusy=false,firmwarePolling=false;
function renderFirmware(){const s=firmwareStatus;if(!s)return;$('firmwareVersion').textContent=s.version;$('autoUpdate').checked=s.automatic;const busy=firmwareBusy||[1,3,4].includes(s.phase);$('autoUpdate').disabled=busy;$('checkFirmware').disabled=busy||!s.wifi;$('installFirmware').disabled=busy||!s.wifi||!s.available;
const errors=['','Lamp is offline.','Waiting for internet time. Try again shortly.','Could not reach the release server.','Release information was invalid.','A USB partition upgrade is required.','Download or verification failed. Retry manually.','Could not save update settings.','Not enough memory to start the updater.'];
$('firmwareStatus').textContent=s.phase===3?'Installing firmware… '+s.progress+'%':s.phase===4?'Update verified. Restarting; refresh this page shortly.':!s.wifi?'Connect the lamp to home Wi-Fi with internet access.':s.phase===1?'Checking for updates…':s.phase===5?errors[s.error]||'Update failed.':s.available?'Firmware '+s.latest+' is available.':s.latest==='0.0.0'?'No published update detected yet.':'Firmware is up to date.';if(bannerOwner==='firmware')status($('firmwareStatus').textContent,'firmware');}
async function pollFirmware(){if(firmwarePolling)return;firmwarePolling=true;try{const r=await fetch('/api/firmware',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Could not read firmware status.');firmwareStatus=await r.json();renderFirmware()}catch(e){firmwareStatus=null;$('firmwareStatus').textContent='Lamp unavailable. Reconnect or refresh after restart.';if(bannerOwner==='firmware')status($('firmwareStatus').textContent,'firmware');['autoUpdate','checkFirmware','installFirmware'].forEach(id=>$(id).disabled=true)}finally{firmwarePolling=false}}
async function firmwareAction(action,data={}){if(firmwareBusy)return;firmwareBusy=true;renderFirmware();try{status(await request('/api/firmware/'+action,data),action==='automatic'?'general':'firmware')}catch(e){status(e.message)}finally{await pollFirmware();firmwareBusy=false;renderFirmware()}}
$('checkFirmware').onclick=()=>firmwareAction('check');$('installFirmware').onclick=()=>firmwareAction('install');$('autoUpdate').onchange=()=>firmwareAction('automatic',{enabled:Number($('autoUpdate').checked)});
$('geometryForm').onsubmit=async e=>{e.preventDefault();const midpoint=Number($('midpoint').value);if(!Number.isInteger(midpoint)||midpoint<0||midpoint>Number($('midpoint').max)){$('geometryStatus').textContent='Choose a boundary within the current strip.';return;}$('saveGeometry').disabled=true;try{$('geometryStatus').textContent=await request('/api/geometry',{midpoint})}catch(e){$('geometryStatus').textContent=e.message}finally{$('saveGeometry').disabled=false}};
function audioLabels(){$('audioGainValue').value=$('audioGain').value;$('audioScaleValue').value=(Number($('audioScale').value)/100).toFixed(2)+'×';}
$('audioGain').oninput=audioLabels;$('audioScale').oninput=audioLabels;
$('saveAudio').onclick=async()=>{const gain=Number($('audioGain').value),gate=Number($('audioGate').value),scale=Number($('audioScale').value);if(!Number.isInteger(gain)||gain<1||gain>64||!Number.isInteger(gate)||gate<0||gate>1024||!Number.isInteger(scale)||scale<100||scale>400){$('audioStatus').textContent='Check sensitivity and noise gate ranges.';return;}$('saveAudio').disabled=true;try{$('audioStatus').textContent=await request('/api/audio',{enabled:Number($('microphoneInstalled').checked),gain,gate,scale})}catch(e){$('audioStatus').textContent=e.message;$('saveAudio').disabled=false}};
$('testAudio').onclick=async()=>{$('testAudio').disabled=true;try{await request('/api/audio/test',{});for(let i=0;i<10;++i){await new Promise(resolve=>setTimeout(resolve,1000));const r=await fetch('/api/audio',{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw Error('Could not read microphone status.');const a=await r.json();$('audioStatus').textContent=a.error?'Capture error '+a.error:a.valid?'Level '+a.level+'/255 • RMS '+a.rms+' • Peak '+a.peak+' • '+(a.signalSeen?'Signal observed (not a hardware identity check).':'No varying signal observed; check wiring if sound is present.'):'Microphone warming up or capture stopped.';}}catch(e){$('audioStatus').textContent=e.message}finally{$('testAudio').disabled=false}};
load();pollFirmware();if(typeof setInterval==='function')setInterval(pollFirmware,5000);
</script></body></html>)HTML";
