import test from 'node:test';import assert from 'node:assert/strict';
import {FirmwareFleetTrust} from '../src/firmware-fleet-trust.js';
function setup(){const saved=new Map(),calls=[],entries=[{id:'aabbccddeeff',deviceId:'paired'}];const transport={id:'paired',identity:entries[0].id,epoch:1,control:{capabilities:['control','firmware-relay']},request:async(path,data)=>{calls.push({path,data});return {version:1,paired:true,fleetId:'0123456789abcdef',automatic:false};}};const trust=new FirmwareFleetTrust({getPairedLamps:()=>entries,credential:async(id,value)=>{if(value!==undefined)saved.set(id,value);return {value:saved.get(id)||''};}});return {saved,calls,entries,transport,trust};}
test('all paired lamps across groups receive one securely stored fleet credential without enabling auto updates',async()=>{const {trust,transport,entries,calls,saved}=setup();await trust.provision(transport);entries.push({id:'112233445566',deviceId:'second'});await trust.provision({...transport,identity:entries[1].id,id:'second'});assert.equal(calls.length,2);assert.equal(calls[0].data.key,calls[1].data.key);assert.equal(saved.size,1);assert.equal(calls[0].path,'/api/firmware/fleet');assert.match(calls[0].data.key,/^[a-f0-9]{32}$/);assert.deepEqual(Object.keys(calls[0].data),['key']);});
test('older firmware is left untouched',async()=>{const {trust,transport,calls}=setup();transport.control.capabilities=['control'];assert.deepEqual(await trust.provision(transport),{supported:false});assert.equal(calls.length,0);});
test('network discovery alone does not authorize firmware trust',async()=>{const {trust,transport,entries,calls}=setup();entries.length=0;await assert.rejects(trust.provision(transport),/Only lamps paired/);assert.equal(calls.length,0);});
test('key creation and provisioning are serialized across concurrent lamps',async()=>{const {trust,transport,calls,saved}=setup();await Promise.all([trust.provision(transport),trust.provision(transport)]);assert.equal(calls.length,1);assert.equal(saved.size,1);});
test('invalid saved credential is not replaced silently',async()=>{const {trust,transport,calls,saved}=setup();saved.set('coollamp-firmware-fleet-v1','bad');await assert.rejects(trust.provision(transport),/preserved/);assert.equal(calls.length,0);assert.equal(saved.get('coollamp-firmware-fleet-v1'),'bad');});
test('readback failure prevents sending a credential that cannot be recovered',async()=>{const {transport}=setup();let calls=0;const trust=new FirmwareFleetTrust({getPairedLamps:()=>[{id:transport.identity,deviceId:transport.id}],credential:async()=>{++calls;return {value:''};}});await assert.rejects(trust.provision(transport),/securely/);assert.equal(calls,3);});
test('provisioning rechecks cancellation immediately before the queued paired-BLE write',async()=>{
 const {trust,transport,calls}=setup();let release,current=true;
 transport.request=async(path,data,epoch,fence)=>{await new Promise(resolve=>release=resolve);fence();calls.push({path,data});return {version:1,paired:true,fleetId:'0123456789abcdef'};};
 const pending=trust.provision(transport,{isCurrent:()=>current});await new Promise(resolve=>setTimeout(resolve,1));current=false;release();await assert.rejects(pending,error=>error.cancelled===true);assert.equal(calls.length,0);
});
